early bash version check

diff --git a/ove b/ove
--- a/ove
+++ b/ove
@@ -40,6 +40,32 @@ if [ "${i}" -eq 1 ]; then
 fi
 unset i
 
+function ove_version_check_early {
+	local ret=0
+
+	if command -v dpkg > /dev/null; then
+		if ! \dpkg --compare-versions ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} ge 4.3; then
+			ret=1
+		fi
+	else
+		if [ ${BASH_VERSINFO[0]} -lt 4 ]; then
+			ret=1
+		elif [ ${BASH_VERSINFO[0]} -eq 4 ] && [ ${BASH_VERSINFO[1]} -lt 3 ]; then
+			ret=1
+		fi
+	fi
+
+	if [ ${ret} -ne 0 ]; then
+		echo "error: bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is too old. I need bash>=4.3"
+	fi
+
+	return ${ret}
+}
+
+if ! ove_version_check_early; then
+	return 1
+fi
+
 function ove_read_config_validate_name {
 	local re="^[a-zA-Z_]{1,}[a-zA-Z0-9_]{0,}$"
 	local var="$1"
@@ -224,7 +250,7 @@ function ove_unsource {
 	# unset old ove[-_] functions
 	unset -f $(compgen -A function | \
 		\grep -E '^ove($|[-_])' | \
-		\grep -E -v "ove_read_config|ove-unsource|${FUNCNAME[0]}" | \
+		\grep -E -v "ove_read_config|ove-unsource|${FUNCNAME[0]}|ove_version_check_early" | \
 		\awk '{print $1}')
 
 	# unset old ove_/OVE_ variables
@@ -271,26 +297,6 @@ function ove_welcome_msg {
 		echo
 		ove_echo_note_noprefix "due to a bug in ${ove_cmd2pathname["script"]:?} 2.31/2.32 (you have ${script_ver}), it's not possible to Ctrl-C any OVE command. Upgrade package: '$(ove_command_to_package script)'."
 	fi
-}
-
-function ove_version_check_early {
-	local ret=0
-
-	if command -v dpkg > /dev/null; then
-		\dpkg --compare-versions ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} ge 4.3 || ret=1
-	else
-		if [ ${BASH_VERSINFO[0]} -lt 4 ]; then
-			ret=1
-		elif [ ${BASH_VERSINFO[0]} -eq 4 ] && [ ${BASH_VERSINFO[1]} -lt 3 ]; then
-			ret=1
-		fi
-	fi
-
-	if [ ${ret} -ne 0 ]; then
-		echo "error: bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is too old. I need bash>=4.3"
-	fi
-
-	return ${ret}
 }
 
 function ove_version_check {
@@ -362,8 +368,8 @@ function ove_main {
 	# set OVE_OS_* variables ('ove_deps' need them)
 	ove_determine_dist_version_and_pack_manager
 
-	# shell version and dependency checks
-	if ! ove_version_check_early || ! ove_deps; then
+	# dependency checks
+	if ! ove_deps; then
 		ove-unsource
 		return 1
 	fi
