loop/run: clarify

diff --git a/ove b/ove
--- a/ove
+++ b/ove
@@ -1407,7 +1407,7 @@ function ove_inotify_cleanup {
 	${ove_cmd2pathname["find"]:?} ${OVE_OWEL_TMP_DIR}/ -name "inotifywait-*-${1}*" -exec rm {} \;
 }
 
-# $1  : timeout in sec
+# $1  : interval in sec
 # $2  : use inotifywait (0 or 1)
 # $3  : max count
 # $4..: command
@@ -1420,21 +1420,21 @@ function ove_loop_command {
 	local f_stderr
 	local files_modified_by_command
 	local i
+	local inotifywait_pid
+	local interval
 	local j
 	local max_count
 	local prefix
 	local read_args
-	local inotifywait_pid
 	local s
 	local sed_expr
-	local _timeout
 	local use_inotify
 
 	if [ $# -lt 4 ]; then
 		return 1
 	fi
 
-	_timeout=$1
+	interval=$1
 	use_inotify=$2
 	max_count=$3
 	shift 3
@@ -1450,7 +1450,7 @@ function ove_loop_command {
 		fi
 		clear
 		if [ "${OVE_TMUX_PANE_HEADER}" = "wide" ]; then
-			ove_echo_cyan_error "${OVE_OWEL_NAME}:ove-${*} [c:${i} t:${_timeout} i:${use_inotify} m:${max_count}]"
+			ove_echo_cyan_error "${OVE_OWEL_NAME}:ove-${*} [c:${i} t:${interval} i:${use_inotify} m:${max_count}]"
 		elif [ "${OVE_TMUX_PANE_HEADER}" = "short" ]; then
 			ove_echo_cyan_error_noprefix "$(${ove_cmd2pathname["date"]:?} '+%Y-%m-%d %H:%M:%S'):ove-${*}"
 		elif [ "${OVE_TMUX_PANE_HEADER}" = "off" ]; then
@@ -1683,7 +1683,7 @@ function ove_loop_command {
 				eval ${ove_cmd2pathname["sed"]:?} -i $sed_expr ${files_modified_by_command}.uniq
 			fi
 
-			if ! ove_inotifywait ${_timeout} ${files_modified_by_command}.uniq; then
+			if ! ove_inotifywait ${interval} ${files_modified_by_command}.uniq; then
 				ove_echo_error_noprefix "inotifywait failed"
 				echo
 				read -r -p "press ENTER to proceed (time-out in 30 sec) " -t 30
@@ -1695,8 +1695,8 @@ function ove_loop_command {
 				${ove_cmd2pathname["sleep"]:?} $((RANDOM%3 + 3))
 			fi
 		else
-			if [ "${_timeout}" != "0" ]; then
-				read_args="-t ${_timeout}"
+			if [ "${interval}" != "0" ]; then
+				read_args="-t ${interval}"
 			fi
 			# shellcheck disable=SC2229
 			read -n 1 -s -r -p '' ${read_args}
@@ -1785,7 +1785,7 @@ function ove_validate_int_float {
 	return 0
 }
 
-# run:|t c:run one command 'c' in terminal/tmux with timeout 't' (0 = no timeout):UTIL
+# run:|t c:run one command 'c' and linger 't' seconds on output (0 = until keypress):UTIL
 function ove-run {
 	ove_entry || return
 
@@ -1794,8 +1794,8 @@ function ove-run {
 	local header
 	local num_panes
 	local read_args
-	local _timeout
 	local target_window
+	local t_linger
 	local tmux_cmd
 	local tmux_opt
 
@@ -1805,11 +1805,11 @@ function ove-run {
 	fi
 
 	if [ $# -eq 0 ]; then
-		read -r -p "command timeout in sec (default 0 = no timeout): "
+		read -r -p "seconds to linger on output (default 0 = until keypress): "
 		if [ "${REPLY}" = "" ]; then
-			_timeout=0
+			t_linger=0
 		else
-			_timeout=${REPLY}
+			t_linger=${REPLY}
 		fi
 		read -r -p "command: "
 		if [ "${REPLY}" = "" ]; then
@@ -1818,26 +1818,26 @@ function ove-run {
 			cmd=${REPLY}
 		fi
 	else
-		_timeout=$1
+		t_linger=$1
 		shift
 		cmd=$*
 	fi
 
-	if ! ove_validate_int_float "${_timeout}"; then
+	if ! ove_validate_int_float "${t_linger}"; then
 		ove_command_usage
-		echo "error: format issues '${_timeout}'" 1>&2
+		echo "error: format issues '${t_linger}'" 1>&2
 		return 1
 	fi
 
 	# turn off monitor mode to get rid of "Done" messages
 	set +m
-	if [ "${_timeout}" != "0" ]; then
-		read_args="-t ${_timeout}"
+	if [ "${t_linger}" != "0" ]; then
+		read_args="-t ${t_linger}"
 	fi
 
 	if ove_sanity_check_tmux 2> /dev/null; then
 		if [ "${OVE_TMUX_PANE_HEADER}" = "wide" ]; then
-			header="ove_echo_cyan_error ${OVE_OWEL_NAME}:${cmd} [t:${_timeout}]"
+			header="ove_echo_cyan_error ${OVE_OWEL_NAME}:${cmd} [t:${t_linger}]"
 		elif [ "${OVE_TMUX_PANE_HEADER}" = "short" ]; then
 			header="ove_echo_cyan_error_noprefix $(${ove_cmd2pathname["date"]:?} '+%Y-%m-%d %H:%M:%S'):${cmd}"
 		elif [ "${OVE_TMUX_PANE_HEADER}" = "tmux" ]; then
@@ -1961,14 +1961,14 @@ function ove-loop-close {
 	ove_kill_procs 1 0.2 $(${ove_cmd2pathname["pgrep"]:?} -f "inotifywait.*${OVE_OWEL_TMP_DIR}")
 }
 
-# loop:|[timeout|x] [inotify|x] [max-count|x] command]:loop one OVE command:UTIL
+# loop:|[interval|x] [inotify|x] [max-count|x] command]:repeatedly run a command with optional file watch:UTIL
 function ove-loop {
 	ove_entry || return
 
 	local _cmd
 	local cmd
 	local max_count
-	local _timeout
+	local interval
 	local use_inotify
 
 	if [ $# -gt 0 ] && [ $# -lt 4 ]; then
@@ -1977,11 +1977,11 @@ function ove-loop {
 	fi
 
 	if [ $# -eq 0 ]; then
-		read -r -p "command timeout in sec (default 0 = no timeout): "
+		read -r -p "interval in sec (default 0 = until keypress): "
 		if [ "${REPLY}" = "" ]; then
-			_timeout=0
+			interval=0
 		else
-			_timeout=${REPLY}
+			interval=${REPLY}
 		fi
 		read -r -p "inotify 0=no 1=yes (default 0): "
 		if [ "${REPLY}" = "" ]; then
@@ -2003,14 +2003,14 @@ function ove-loop {
 		fi
 	else
 		if [ "${1,}" = "x" ]; then
-			read -r -p "command timeout in sec (0 = no timeout): "
+			read -r -p "interval in sec (default 0 = until keypress): "
 			if [ "${REPLY}" = "" ]; then
-				_timeout=0
+				interval=0
 			else
-				_timeout=${REPLY}
+				interval=${REPLY}
 			fi
 		else
-			_timeout=$1
+			interval=$1
 		fi
 
 		if [ "${2,}" = "x" ]; then
@@ -2039,9 +2039,9 @@ function ove-loop {
 		cmd=$*
 	fi
 
-	if ! ove_validate_int_float "${_timeout}"; then
+	if ! ove_validate_int_float "${interval}"; then
 		ove_command_usage
-		echo "error: format issues '${_timeout}'" 1>&2
+		echo "error: format issues '${interval}'" 1>&2
 		return 1
 	fi
 
@@ -2073,12 +2073,12 @@ function ove-loop {
 		${ove_cmd2pathname["tmux"]:?} split-window -h "\
 			source ${OVE_BASE_DIR}/ove; \
 			ove_init; \
-			ove_loop_command ${_timeout} ${use_inotify} ${max_count} '${cmd}'"
+			ove_loop_command ${interval} ${use_inotify} ${max_count} '${cmd}'"
 
 		${ove_cmd2pathname["tmux"]:?} select-layout ${OVE_TMUX_LAYOUT}
 		${ove_cmd2pathname["tmux"]:?} select-pane -t 0
 	else
-		ove_loop_command ${_timeout} ${use_inotify} ${max_count} "${cmd}"
+		ove_loop_command ${interval} ${use_inotify} ${max_count} "${cmd}"
 	fi
 }
 
