unittest: uniq dir

diff --git a/ove b/ove
--- a/ove
+++ b/ove
@@ -13613,16 +13613,13 @@ function ove_unittest_preparations {
 	local nbr_of_projs
 	local nbr_of_repos
 	local nbr_of_systests
-	local unittest_dir
 
 	nbr_of_files_per_repo=$1
 	nbr_of_projs=$2
 	nbr_of_repos=$3
 	nbr_of_systests=$4
 
-	unittest_dir="${OVE_OWEL_TMP_DIR}/unittest"
-
-	echo "${unittest_dir}"
+	echo "${unittest_dir:?}"
 	[ -d ${unittest_dir} ] && \
 		${ove_cmd2pathname["rm"]:?} -rf ${unittest_dir}
 	${ove_cmd2pathname["mkdir"]:?} -p ${unittest_dir}/.ove
@@ -13776,6 +13773,7 @@ function ove_unittest {
 
 	echo "nbr_of_files_per_repo: ${nbr_of_files_per_repo} nbr_of_projs: ${nbr_of_projs} nbr_of_repos: ${nbr_of_repos} nbr_of_systests: ${nbr_of_systests}"
 
+	unittest_dir="$(mktemp -d -p ${OVE_OWEL_TMP_DIR})"
 	if ! ove_unittest_preparations ${nbr_of_files_per_repo} ${nbr_of_projs} ${nbr_of_repos} ${nbr_of_systests}; then
 		return 1
 	fi
@@ -13809,7 +13807,7 @@ function ove_unittest {
 		((tot_tests+=1))
 	fi
 
-	cd ${OVE_OWEL_TMP_DIR}/unittest || return 1
+	cd ${unittest_dir} || return 1
 
 	export nbr_of_systests=${tot_tests}
 	export nbr_of_projs=${nbr_of_projs}
@@ -13818,6 +13816,9 @@ function ove_unittest {
 	for t in $tests; do
 		$OVE_DIR/tests/$t
 	done
+
+	# cleanup
+	rm -rf "${unittest_dir:?}"
 }
 
 # unittest:[test...]:run all/specific unit tests:INTERNAL
