loglevel: tcpconnect

diff --git a/ove b/ove
--- a/ove
+++ b/ove
@@ -1152,6 +1152,7 @@ function ove-loop {
 
 function ove {
 	local args
+	local bcc_tool
 	local candidates
 	local cmd
 	local re
@@ -1224,7 +1225,7 @@ function ove {
 				[[ "${script_help}" == *"-f"* ]] && script_opts+="-f "
 			fi
 
-			if [ ${OVE_LOGLEVEL} -gt 2 ] && [ ${OVE_LOGLEVEL} -lt 8 ]; then
+			if [ ${OVE_LOGLEVEL} -gt 2 ] && [ ${OVE_LOGLEVEL} -lt 9 ]; then
 				[ -e ${OVE_PROJECT_TMP_DIR}/trace-${cmd} ] && \
 					\rm -rf ${OVE_PROJECT_TMP_DIR}/trace-${cmd}
 				\mkdir -p ${OVE_PROJECT_TMP_DIR}/trace-${cmd}
@@ -1237,19 +1238,25 @@ function ove {
 					strace_expression="execve"
 				fi
 
-				if [ ${OVE_LOGLEVEL} -eq 7 ]; then
+				if [ ${OVE_LOGLEVEL} -eq 7 ] || [ ${OVE_LOGLEVEL} -eq 8 ]; then
+					if [ ${OVE_LOGLEVEL} -eq 7 ]; then
+						bcc_tool="execsnoop"
+					else
+						bcc_tool="tcpconnect"
+					fi
+
 					if [ ${EUID} != 0 ]; then
 						if ! sudo -n true; then
 							if ! sudo true; then
-								ove_echo_error_noprefix "'execsnoop' need non-interactive 'sudo'"
+								ove_echo_error_noprefix "'${bcc_tool}' need non-interactive 'sudo'"
 								return 1
 							fi
 						fi
 						OVE_TRACE_CMD="sudo "
 					fi
-					OVE_TRACE_CMD+="python3 /usr/share/bcc/tools/execsnoop "
+					OVE_TRACE_CMD+="python3 /usr/share/bcc/tools/${bcc_tool} "
 					OVE_TRACE_CMD+="-t "
-					OVE_TRACE_CMD+="-u ${USER} "
+					OVE_TRACE_CMD+="-u ${EUID} "
 					OVE_TRACE_CMD+="> ${OVE_PROJECT_TMP_DIR}/trace-${cmd}/trace-${cmd} "
 					OVE_TRACE_CMD+="2> /dev/null"
 				else
@@ -1277,12 +1284,13 @@ function ove {
 					while true; do [ -e ${OVE_PROJECT_TMP_DIR}/trace.pid ] && break; done
 
 					# launch trace in background and let it start up
-					if [ ${OVE_LOGLEVEL} -eq 7 ]; then
+					if [ ${OVE_LOGLEVEL} -eq 7 ] || [ ${OVE_LOGLEVEL} -eq 8 ]; then
 						(eval ${OVE_TRACE_CMD} &)
+						sleep 2
 					else
 						(${OVE_TRACE_CMD} -p $(\cat ${OVE_PROJECT_TMP_DIR}/trace.pid) &)
+						sleep 1
 					fi
-					sleep 1
 					true > ${OVE_PROJECT_TMP_DIR}/trace.cont
 				} &
 			fi
@@ -1296,11 +1304,11 @@ function ove {
 			ret=$?
 
 			if [ -n "${OVE_TRACE_CMD+x}" ]; then
-				if [ ${OVE_LOGLEVEL} -eq 7 ]; then
+				if [ ${OVE_LOGLEVEL} -eq 7 ] || [ ${OVE_LOGLEVEL} -eq 8 ]; then
 					if [ ${EUID} != 0 ]; then
-						sudo pkill -SIGINT -f execsnoop
+						sudo pkill -SIGINT -f ${bcc_tool}
 					else
-						\pkill -SIGINT -f execsnoop
+						\pkill -SIGINT -f ${bcc_tool}
 					fi
 				else
 					\pkill -SIGINT -f strace
@@ -1318,7 +1326,7 @@ function ove {
 						ove_analyze_strace_connect ${OVE_PROJECT_TMP_DIR}/trace-${cmd}
 					elif [ ${OVE_LOGLEVEL} -eq 6 ]; then
 						ove_strace_create_graph ${OVE_PROJECT_TMP_DIR}/trace-${cmd} ${cmd}
-					elif [ ${OVE_LOGLEVEL} -eq 7 ]; then
+					elif [ ${OVE_LOGLEVEL} -eq 7 ] || [ ${OVE_LOGLEVEL} -eq 8 ]; then
 						\head -n -1 ${OVE_PROJECT_TMP_DIR}/trace-${cmd}/trace-${cmd}
 					fi
 					break
@@ -5768,12 +5776,13 @@ function ove-version {
 
 # loglevel:[LEVEL] :show or change loglevel [0-7]
 function ove-loglevel {
+	local bcc_tool
 	local prefix
 	local sysctl_f
 
 	set +x
-	if [ $# -eq 1 ] && ! [[ "${1}" =~ ^[0-7]$ ]]; then
-		echo "error: try 0-7"
+	if [ $# -eq 1 ] && ! [[ "${1}" =~ ^[0-8]$ ]]; then
+		echo "error: try 0-8"
 		return 1
 	elif [ $# -eq 1 ]; then
 		if [ $1 -gt 2 ] && [ $1 -lt 7 ]; then
@@ -5800,21 +5809,27 @@ function ove-loglevel {
 			fi
 		fi
 
-		if [ $1 -eq 7 ]; then
+		if [ $1 -ge 7 ] && [ $1 -le 9 ]; then
+			if [ ${1} -eq 7 ]; then
+				bcc_tool="execsnoop"
+			else
+				bcc_tool="tcpconnect"
+			fi
+
 			if ! command -v python3 > /dev/null; then
-				ove_echo_command_not_found "python3" "Needed by 'execsnoop'."
+				ove_echo_command_not_found "python3" "Needed by '${bcc_tool}'."
 				return 1
 			fi
 
-			if ! [ -e /usr/share/bcc/tools/execsnoop ]; then
-				ove_echo_error_noprefix "'/usr/share/bcc/tools/execsnoop' not found."
+			if ! [ -e /usr/share/bcc/tools/${bcc_tool} ]; then
+				ove_echo_error_noprefix "'/usr/share/bcc/tools/${bcc_tool}' not found."
 				return 1
 			fi
 
 			if [ ${EUID} != 0 ]; then
 				if ! sudo -n true; then
 					if ! sudo true; then
-						ove_echo_error_noprefix "'execsnoop' need non-interactive 'sudo'"
+						ove_echo_error_noprefix "'${bcc_tool}' need non-interactive 'sudo'"
 						return 1
 					fi
 				fi
@@ -5840,6 +5855,7 @@ function ove-loglevel {
 		echo "5: connect analysis     [strace]"
 		echo "6: graph analysis       [strace]"
 		echo "7: execsnoop            [bcc]"
+		echo "8: tcpconnect           [bcc]"
 		break
 	done | \grep -E --color "$|${OVE_LOGLEVEL}"
 
