loop: less inotify watchers

diff --git a/ove b/ove
--- a/ove
+++ b/ove
@@ -297,29 +297,30 @@ function ove_analyze_strace_connect {
 }
 
 # $1: timeout in seconds
+# $2: files to watch. Passed on to inotifywait --fromfile
 function ove_inotifywait {
-	local f
-	local files
+	local ret
 
-	files=$(mktemp -u -p ${OVE_PROJECT_TMP_DIR} inotifywait-fromfile-XXXXXXXXXX)
-
-	for f in $(ove-ls-files); do
-		[ -f ${f} ] && echo ${f}
-	done > ${files}
+	! [ -e ${2} ] && return 1
+	! [ $(cat ${2} | wc -l) -ne 0 ] && return 1
 
 	sleep 0.01
 	inotifywait \
-		-r \
-		-t $1 \
+		-t ${1} \
 		-qq \
 		--event modify \
 		--event delete_self \
 		--event create \
 		--event delete \
-		--exclude '.git' \
-		--fromfile ${files}
+		--fromfile ${2}
+	ret=$?
+
 	sleep 0.01
-	rm ${files}
+	[ $ret -eq 1 ] && return 1 || return 0
+}
+
+function ove_inotify_cleanup {
+	find ${OVE_PROJECT_TMP_DIR}/ -name "inotifywait-*-${1}*" -exec rm {} \;
 }
 
 # $1: timeout in sec
@@ -327,9 +328,14 @@ function ove_inotifywait {
 # $3: max count
 # $*: command
 function ove_loop_command {
+	local all_files
+	local cmd
 	local counter
+	local f
+	local files_modified_by_command
 	local max_count
 	local read_args
+	local inotifywait_pid
 	local timeout
 	local use_inotify
 
@@ -345,10 +351,72 @@ function ove_loop_command {
 		[ ${max_count} -ne 0 ] && [ ${counter} -gt ${max_count} ] && break
 		clear
 		ove_echo_cyan_error "ove-${*} [c:${counter} t:${timeout} i:${use_inotify} m:${max_count}]"
+
+		# inotify: first iteration?
+		if [ ${use_inotify} -eq 1 ] && [ ${counter} -eq 1 ]; then
+			all_files=$(mktemp -u -p ${OVE_PROJECT_TMP_DIR} inotifywait-fromfile-XXXXXXXXXX)
+
+			# trap to be able to cleanup files
+			trap "ove_inotify_cleanup ${all_files: -10}" EXIT
+
+			# start inotifywait in monitor mode in the background
+			# monitor all files (for now)
+			cmd='for f in $(git ls-files); do [ -f ${f} ] && echo $PWD/$f; done; echo $PWD/.git'
+			ove_revtab_forall_parallel "${cmd}" > ${all_files}
+			files_modified_by_command=${OVE_PROJECT_TMP_DIR}/inotifywait-${1}-${all_files: -10}
+
+			if [ $(cat /proc/sys/fs/inotify/max_user_watches) -lt $(cat ${all_files} | wc -l) ]; then
+				ove_echo_error_noprefix "You need to increase the number of inotify user watches. Try:"
+				echo
+				echo "$ sudo bash -c 'echo $(cat ${all_files} | wc -l) > /proc/sys/fs/inotify/max_user_watches'"
+				read -p ""
+				return 1
+			fi
+
+			inotifywait \
+				-q \
+				-m \
+				--format '%w%f' \
+				--fromfile ${all_files} > ${files_modified_by_command} &
+			inotifywait_pid=${!}
+			# let inotify start up
+			sleep 1
+
+			# still running?
+			if ! kill -0 ${inotifywait_pid} > /dev/null 2>&1; then
+				return 1
+			fi
+		fi
+
+		# run the command
 		OVE_PAGER='tee /dev/null' ove-${1} ${*:2}
+
+		# inotify: first iteration?
+		if [ ${use_inotify} -eq 1 ] && [ ${counter} -eq 1 ]; then
+			sleep 1
+			kill -9 ${inotifywait_pid} &> /dev/null
+			wait &> /dev/null
+			rm ${all_files}
+
+			# remove doublets and only regular files
+			for f in $(sort -u ${files_modified_by_command}); do
+				[ -f ${f} ] && echo ${f};
+			done > ${files_modified_by_command}.uniq
+			rm ${files_modified_by_command}
+			if [ $(cat ${files_modified_by_command}.uniq | wc -l) -eq 0 ]; then
+				use_inotify=0
+				ove_echo_cyan_error "0 files touched, not using inotifywait"
+			else
+				echo
+				echo "$(cat ${files_modified_by_command}.uniq | wc -l) uniq file(s) was touched by '${1} ${*:2}': ${files_modified_by_command}.uniq"
+			fi
+		fi
+
 		echo -
 		if [ ${use_inotify} -eq 1 ]; then
-			ove_inotifywait ${timeout}
+			if ! ove_inotifywait ${timeout} ${files_modified_by_command}.uniq; then
+				break
+			fi
 		else
 			[ "${timeout}" -gt 0 ] && read_args="-t ${timeout}"
 			read -n 1 -s -r -p '' ${read_args}
