strace graph visualizer

diff --git a/ove b/ove
--- a/ove
+++ b/ove
@@ -203,48 +203,57 @@ function ove_main {
 	fi
 }
 
-# $1: directory with strace pid files
-function ove_analyze_strace_execve_timing {
+# $1: pid
+function ove_strace_execve_one_pid {
 	local cmd
-	local diff
-	local f
+	local exit_code
 	local line
 	local t0
-	local t1
 
-	! [ -d "$1" ] && return 1
-
-	set -o noglob
-	for f in $(find $1 -type f); do
-		line=$(head -1 ${f})
-		if [[ "${line}" == *"execve"* ]]; then
-			cmd=$(echo ${line} | grep -o '\[.*')
-			t0=${line%% *}
+	cmd=
+	pid=$1
+	while read -r line; do
+		if [[ "${line}" == *" execve("* ]] && ! [[ "${line}" == *"ENOENT"* ]]; then
+			cmd=${line##* [\"}
+			cmd=${cmd%%\"]*}
+			cmd=${cmd//\", \"/ }
+			t0=$(ove_strace_get_t0 ${pid})
+			[ "${cmd}" == "" ] && continue
+			exit_code=$(ove_strace_get_exit_code ${pid})
 			if [ ${OVE_LOGLEVEL} -eq 3 ]; then
-				echo "${t0}:${cmd}"
+				echo "${t0}:${pid}:${exit_code}:${cmd}"
 			elif [ ${OVE_LOGLEVEL} -eq 4 ]; then
-				t1=$(tail -1 ${f} | awk '{print $1}')
-				diff=$(awk "BEGIN{printf \"%.6f\n\", (${t1} - ${t0})}")
-				echo "${diff}:${cmd}"
+				echo "$(ove_strace_get_duration_s ${pid}):${pid}:${exit_code}:${cmd}"
 			fi
+			continue
 		fi
-	done | \
-		sed -e 's|:\[|: |g' -e 's|\].*=||g' | \
-		tr -d '",' | \
-		sort -n$([ ${OVE_LOGLEVEL} -eq 4 ] && echo r)
+	done <<< "${all_files[$1]}"
 }
 
 # $1: directory with strace pid files
-function ove_analyze_strace_connect {
+function ove_analyze_strace_execve_timing {
+	local all_files
 	local f
-	local execve
-	local ip
-	local ip_lookup
-	local line
-	local port
-	local port_lookup
+	local pid
 
 	! [ -d "$1" ] && return 1
+
+	declare -A all_files
+	while true; do
+		for f in $(find $1 -type f); do
+			pid=${f##*.}
+			all_files[${pid}]="$(<${f})"
+			ove_strace_execve_one_pid ${pid} &
+		done
+		wait
+		break
+	done | sort -n$([ ${OVE_LOGLEVEL} -eq 4 ] && echo r)
+}
+
+# $1: IPv4 address
+function ove_ip2host {
+	local ip
+	local ip_lookup
 
 	if ! command -v dig > /dev/null; then
 		ove_echo_error_noprefix "error: 'dig' is not found"
@@ -256,48 +265,316 @@ function ove_analyze_strace_connect {
 		return 1
 	fi
 
-	for f in $(find $1 -type f); do
-		# IPv4 only for now
-		for line in $(grep -E -o 'port=htons\([0-9]+\).*[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ${f} | tr ' ' '-'); do
-			ip=$(echo ${line} | \
-				grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
+	ip=${1}
 
-			# ignore loopback
-			[[ ${ip} == 127* ]] && continue
+	if [[ ${ip} == 127* ]]; then
+		ip_lookup="localhost"
+	else
+		ip_lookup=$(dig +short -x ${ip} | \
+			tr '\n' ' ' | \
+			xargs)
+		[ "${ip_lookup}" == "" ] && return
 
-			ip_lookup=$(dig +short -x ${ip} | \
-				tr '\n' ' ' | \
+		ip_lookup=${ip_lookup::-1}
+		if [ "${ip_lookup}" == "" ]; then
+			ip_lookup=$(whois ${ip} | \
+				grep OrgName | \
+				cut -d: -f2- | \
 				xargs)
-			if [ "${ip_lookup}" == "" ]; then
-				ip_lookup=$(whois ${ip} | \
-					grep OrgName | \
-					cut -d: -f2- | \
-					xargs)
-			fi
+		fi
+	fi
 
-			[ "${ip_lookup}" == "" ] && ip_lookup="N/A"
-			execve=$(grep -m1 execve ${f})
-			if [ "${execve}" == "" ]; then
-				execve="$(grep -m1 connect ${f} | \
-					awk '{print $1}') pid $(basename ${f} | cut -d'.' -f2)"
-			fi
+	echo ${ip_lookup}
+}
 
+# $1: port
+function ove_port2service {
+	local port
+	local port_service
+
+	port=${1}
+
+	if [ -e /etc/services ]; then
+		port_service=$(grep -m1 -w ${port} /etc/services | \
+			awk '{print $1}')
+	fi
+
+	echo "${port_service}"
+}
+
+function ove_strace_connect_one_pid {
+	local cmd
+	local str
+	local ip
+	local ip_lookup
+	local line
+	local port
+	local port_service
+
+	cmd=
+	pid=$1
+	while read -r line; do
+		if [[ "${line}" == *" connect("* ]] && [[ "${line}" == *"htons"* ]]; then
+			t0=${line%% *}
+			ip=$(echo ${line} | grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
 			port=$(echo ${line} | \
-				cut -d'(' -f2- | \
+				cut -d'(' -f3- | \
 				cut -d')' -f1)
+			ip_lookup=$(ove_ip2host ${ip})
+			port_service=$(ove_port2service ${port})
+			cmd=$(ove_strace_get_execve ${pid})
+			[ "${cmd}" == "" ] && cmd="NA"
 
-			if [ -e /etc/services ]; then
-				port_lookup=$(grep -m1 -w ${port} /etc/services | \
-					awk '{print $1}')
-			fi
+			str+="${t0}:${cmd}:${ip}:${ip_lookup}:${port}:${port_service}\n"
+			ip_lookup_no_hyphen=$(echo ${ip_lookup} | tr '-' '_')
+		fi
+	done <<< "${all_files[${pid}]}"
 
-			if [ "${port_lookup}" == "" ]; then
-				port_lookup="N/A"
-			fi
+	[ "${str}" != "" ] && printf "${str}"
+}
 
-			echo "${execve} @ ${ip} @ ${ip_lookup} @ ${port} @ ${port_lookup}"
+# $1: directory with strace pid files
+function ove_analyze_strace_connect {
+	local all_files
+	local f
+	local pid
+
+	! [ -d "$1" ] && return 1
+
+	declare -A all_files
+	while true; do
+		for f in $(find $1 -type f); do
+			pid=${f##*.}
+			all_files[${pid}]="$(<${f})"
+			ove_strace_connect_one_pid ${pid} &
 		done
-	done | sort -n | column -s'@' -t
+		wait
+		break
+	done | sort -n
+}
+
+# $1: pid
+function ove_strace_get_exit_code {
+	local exit_code
+	local strace_file
+
+	strace_file=${all_files[$1]}
+	exit_code=${strace_file##*$'\n'}
+	if [[ "${exit_code}" == *"killed by"* ]]; then
+		exit_code=${exit_code##* killed by }
+		exit_code=${exit_code%% +++}
+	else
+		exit_code=${exit_code##* exited with }
+		exit_code=${exit_code%% +++}
+	fi
+
+	echo ${exit_code}
+}
+
+# $1: pid
+function ove_strace_get_duration_s {
+	local diff
+	local strace_file
+	local t0
+	local t1
+
+	strace_file=${all_files[$1]}
+	t0=${strace_file%% *}
+	t1=${strace_file##*$'\n'}
+	t1=${t1%% *}
+
+	[ "${t0}" == "${t1}" ] && echo "0.000000" && return
+
+	diff=$(awk "BEGIN{printf \"%.6f\n\", (${t1} - ${t0})}")
+	echo ${diff}
+}
+
+# $1: pid
+function ove_strace_get_duration_ms {
+	local diff
+	local strace_file
+	local t0
+	local t1
+
+	strace_file=${all_files[$1]}
+	t0=${strace_file%% *}
+	t1=${strace_file##*$'\n'}
+	t1=${t1%% *}
+
+	[ "${t0}" == "${t1}" ] && echo "0" && return
+
+	diff=$(awk "BEGIN{printf \"%.0f\n\", (${t1} - ${t0}) * 1000}")
+	echo ${diff}
+}
+
+# $1: pid
+function ove_strace_get_t0 {
+	local strace_file
+	local t0
+
+	strace_file=${all_files[$1]}
+	t0=${strace_file%% *}
+	echo ${t0}
+}
+
+# $1: pid
+function ove_strace_get_execve {
+	local cmd
+	local line
+
+	while read -r line; do
+		! [[ "${line}" == *" execve("* ]] && continue
+		[[ "${line}" == *"ENOENT"* ]] && continue
+		cmd=${line##* [\"}
+		cmd=${cmd%%\"]*}
+		cmd=${cmd//\", \"/ }
+	done <<< "${all_files[$1]}"
+
+	echo -e "${cmd}"
+}
+
+# $1: pid
+function ove_run_one_pid {
+	local cmd
+	local duration_ms
+	local duration_s
+	local ip
+	local ip_lookup
+	local ip_lookup_no_hyphen
+	local line
+	local out_1
+	local out_2
+	local p
+	local pid
+	local port
+	local port_service
+
+	pid=$1
+
+	duration_ms=$(ove_strace_get_duration_ms ${pid})
+	duration_s=$(ove_strace_get_duration_s ${pid})
+
+	# label START
+	out_1="    ${pid} [label=\"p: ${pid}\l\nt: $(ove_strace_get_t0 ${pid})\l\nd: ${duration_ms} ms (${duration_s} s)\l\n"
+
+	# exit code
+	exit_code=$(ove_strace_get_exit_code ${pid})
+	if [[ "${exit_code}" =~ ^[0-9]+$ ]]; then
+		if [ ${exit_code} -ne 0 ]; then
+			out_1+="e: ${exit_code}\l\n"
+			border_color=$(echo "\"red\"")
+		else
+			border_color=$(echo "\"green\"")
+		fi
+	else
+		out_1+="e: ${exit_code}\l\n"
+		border_color=$(echo "\"black\"")
+	fi
+
+	cmd=
+	out_2=
+	while read -r line; do
+		if [[ "${line}" == *" clone("* ]]; then
+			p=${line##* = }
+			p=${p%% *}
+			! [[ "${p}" =~ ^[0-9]+$ ]] && continue
+			out_2+="    ${pid} -> ${p} [label=clone];"
+			continue
+		elif [[ "${line}" == *" fork("* ]]; then
+			p=${line##* = }
+			p=${p%% *}
+			! [[ "${p}" =~ ^[0-9]+$ ]] && continue
+			out_2+="    ${pid} -> ${p} [label=fork];"
+			continue
+		elif [[ "${line}" == *" vfork("* ]]; then
+			p=${line##* = }
+			p=${p%% *}
+			! [[ "${p}" =~ ^[0-9]+$ ]] && continue
+			out_2+="    ${pid} -> ${p} [label=vfork];"
+			continue
+		elif [[ "${line}" == *" execve("* ]] && ! [[ "${line}" == *"ENOENT"* ]]; then
+			cmd=${line##* [\"}
+			cmd=${cmd%%\"]*}
+			cmd=${cmd//\", \"/ }
+			continue
+		elif [[ "${line}" == *" connect("* ]] && [[ "${line}" == *"htons"* ]]; then
+			[[ "${line}" == *"AF_INET6"* ]] && continue
+			ip=$(echo ${line} | grep -E -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
+			port=$(echo ${line} | \
+				cut -d'(' -f3- | \
+				cut -d')' -f1)
+			ip_lookup=$(ove_ip2host ${ip})
+			[ "${ip_lookup}" == "" ] && ip_lookup=${ip}
+			port_service=$(ove_port2service ${port})
+			out_1+="c: ${ip}|${ip_lookup}|${port}|${port_service}\l\n"
+			ip_lookup_no_hyphen=$(echo ${ip_lookup} | tr '-' '_')
+			out_2+="    $(echo ${ip_lookup_no_hyphen} | cut -d. -f1) [label=\"${ip_lookup}\l\nIP: ${ip}\l\n\" shape=box3d,fontsize=20,style=filled, fillcolor=\"yellow\"];"
+			out_2+="    ${pid} -> $(echo ${ip_lookup_no_hyphen} | cut -d. -f1) [label=\"${port} ${port_service}\"];"
+		fi
+	done <<< "${all_files[$1]}"
+
+	# penwidth based on duration
+	penwidth=${duration_ms}
+	if [ ${duration_ms} -gt 20 ]; then
+		penwidth=20
+	elif [ ${duration_ms} -eq 0 ]; then
+		penwidth=1
+	fi
+
+	out_1+=$(echo -e ${cmd} | fold -w 80 -s | sed -e 's/$/ \\l\\n/g' | tr '\n' ' ' | tr \" \')
+	# label END
+	out_1+="\",color=${border_color},penwidth=${penwidth},fontsize=14,fontcolor=black];"
+
+	echo "${out_1}"
+	[ "${out_2}" != "" ] && echo "${out_2}"
+}
+
+# $1: directory with strace pid files
+# $2: append string to output files
+function ove_strace_create_graph {
+	local all_files
+	local f
+	local o_con
+	local o_dot
+	local o_svg
+	local o_tmp
+	local pid
+
+	! [ -d "$1" ] && return 1
+	[ $# -ne 2 ] && return 2
+
+	o_base="${OVE_PROJECT_TMP_DIR}/strace-${2}"
+	o_dot=${o_base}.dot
+	o_svg=${o_base}.svg
+
+	echo "digraph $(echo ${OVE_PROJECT_NAME} | tr '-' '_') {" > ${o_dot}
+	echo "    nodesep=2" >> ${o_dot}
+	echo "    ranksep=5" >> ${o_dot}
+	echo "    node [margin=1,shape=octagon,nodesep=10];" >> ${o_dot}
+
+	# remove leftovers
+	find ${OVE_PROJECT_TMP_DIR} -name "strace-${2}.dot.*" -print0 | xargs -0 rm &> /dev/null
+
+	declare -A all_files
+	for f in $(find $1 -type f); do
+		pid=${f##*.}
+		all_files[${pid}]="$(<${f})"
+		ove_run_one_pid ${pid} >> ${o_dot}.${pid} &
+	done
+	wait
+
+	# merge all files into one
+	find ${OVE_PROJECT_TMP_DIR} -name "strace-${2}.dot.*" -print0 | xargs -0 cat >> ${o_dot}
+	find ${OVE_PROJECT_TMP_DIR} -name "strace-${2}.dot.*" -print0 | xargs -0 rm
+
+	echo "}" >> ${o_dot}
+
+	echo "${1}"
+	echo "${o_dot}"
+	if command -v dot > /dev/null; then
+		dot -Tsvg ${o_dot} > ${o_svg}
+		echo "${o_svg}"
+	fi
 }
 
 # $1: timeout in seconds
@@ -320,7 +597,7 @@ function ove_inotifywait {
 	ret=$?
 
 	sleep 0.01
-	[ $ret -eq 1 ] && return 1 || return 0
+	[ ${ret} -eq 1 ] && return 1 || return 0
 }
 
 function ove_inotify_cleanup {
@@ -365,7 +642,7 @@ function ove_loop_command {
 
 			# start inotifywait in monitor mode in the background
 			# monitor all files (for now)
-			cmd='for f in $(git ls-files); do [ -f ${f} ] && echo $PWD/$f; done; echo $PWD/.git'
+			cmd='for f in $(git ls-files); do [ -f ${f} ] && echo ${PWD}/${f}; done; echo ${PWD}/.git'
 			ove_revtab_forall_parallel "${cmd}" > ${all_files}
 			files_modified_by_command=${OVE_PROJECT_TMP_DIR}/inotifywait-${1}-${all_files: -10}
 
@@ -642,40 +919,82 @@ function ove {
 				script_opts+="-e "
 			fi
 
-			if [ ${OVE_LOGLEVEL} -gt 2 ] && [ ${OVE_LOGLEVEL} -lt 6 ]; then
+			if [ ${OVE_LOGLEVEL} -gt 2 ] && [ ${OVE_LOGLEVEL} -lt 7 ]; then
 				[ -e ${OVE_PROJECT_TMP_DIR}/strace-${cmd} ] && \
 					rm -rf ${OVE_PROJECT_TMP_DIR}/strace-${cmd}
 				mkdir -p ${OVE_PROJECT_TMP_DIR}/strace-${cmd}
 
 				if [ ${OVE_LOGLEVEL} -eq 5 ]; then
 					strace_expression="connect,execve"
+				elif [ ${OVE_LOGLEVEL} -eq 6 ]; then
+					strace_expression="execve,clone,fork,vfork,connect"
 				else
 					strace_expression="execve"
 				fi
 
-				OVE_ANALYZE_EXECVE="strace \
+				OVE_ANALYZE_EXECVE="sudo \
+					strace \
 					-s 1024 \
 					-q \
 					-o ${OVE_PROJECT_TMP_DIR}/strace-${cmd}/strace-${cmd} \
 					-ff \
+					-T \
 					-e ${strace_expression} \
 					-ttt"
+				export OVE_ANALYZE_EXECVE
 			else
 				unset OVE_ANALYZE_EXECVE
 			fi
 
+			if ! [ -z "${OVE_ANALYZE_EXECVE+x}" ]; then
+				[ -e ${OVE_PROJECT_TMP_DIR}/strace.pid ] && \
+					rm ${OVE_PROJECT_TMP_DIR}/strace.pid
+				[ -e ${OVE_PROJECT_TMP_DIR}/strace.cont ] && \
+					rm ${OVE_PROJECT_TMP_DIR}/strace.cont
+
+				if ! sudo -n true &> /dev/null; then
+					ove_echo_red_noprefix "I'm not able to run sudo without user interaction"
+					ove_echo_red_noprefix "Try to run a command as sudo to prolong the sudo timeout:"
+					echo
+					echo "$ sudo true"
+					return 1
+				fi
+
+				{
+					while true; do [ -e ${OVE_PROJECT_TMP_DIR}/strace.pid ] && break; done
+
+					# launch strace in background and let strace start up
+					(${OVE_ANALYZE_EXECVE} -p $(cat ${OVE_PROJECT_TMP_DIR}/strace.pid) &)
+					sleep 1
+					> ${OVE_PROJECT_TMP_DIR}/strace.cont
+				} &
+			fi
+
+			# turn off monitor mode to get rid of "Done" messages
+			set +m
 			SHELL=$(command -v bash) \
-				${OVE_ANALYZE_EXECVE} script ${script_opts} -q -c \
-				"source ${OVE_BASE_DIR}/ove; ove_init quick && ove-${cmd} ${args}" \
+				script ${script_opts} -q -c \
+				"source ${OVE_BASE_DIR}/ove; ove_init quick; ove-${cmd} ${args}" \
 				${OVE_LAST_COMMAND}
 			ret=$?
 
 			if ! [ -z "${OVE_ANALYZE_EXECVE+x}" ]; then
-				if [ ${OVE_LOGLEVEL} -eq 3 ] || [ ${OVE_LOGLEVEL} -eq 4 ]; then
-					ove_analyze_strace_execve_timing ${OVE_PROJECT_TMP_DIR}/strace-${cmd} | tee -a ${OVE_LAST_COMMAND}
-				elif [ ${OVE_LOGLEVEL} -eq 5 ]; then
-					ove_analyze_strace_connect ${OVE_PROJECT_TMP_DIR}/strace-${cmd} | tee -a ${OVE_LAST_COMMAND}
-				fi
+				sudo pkill -SIGTERM -f strace
+				[ -e ${OVE_PROJECT_TMP_DIR}/strace.pid ] && \
+					rm ${OVE_PROJECT_TMP_DIR}/strace.pid
+				[ -e ${OVE_PROJECT_TMP_DIR}/strace.cont ] && \
+					rm ${OVE_PROJECT_TMP_DIR}/strace.cont
+
+				while true; do
+					if [ ${OVE_LOGLEVEL} -eq 3 ] || [ ${OVE_LOGLEVEL} -eq 4 ]; then
+						ove_analyze_strace_execve_timing ${OVE_PROJECT_TMP_DIR}/strace-${cmd}
+					elif [ ${OVE_LOGLEVEL} -eq 5 ]; then
+						ove_analyze_strace_connect ${OVE_PROJECT_TMP_DIR}/strace-${cmd}
+					elif [ ${OVE_LOGLEVEL} -eq 6 ]; then
+						ove_strace_create_graph ${OVE_PROJECT_TMP_DIR}/strace-${cmd} ${cmd}
+					fi
+					break
+				done | tee -a ${OVE_LAST_COMMAND}
 			fi
 
 			sed -i -e 's/\r$//' -e 's/\x0//' ${OVE_LAST_COMMAND}
@@ -4252,11 +4571,11 @@ function ove-version {
 	echo "OVE [SHA-1: ${OVE_SHA} @ ${OVE_OS} ${OVE_OS_VER}]"
 }
 
-# loglevel:[LEVEL] :show or change loglevel [0-5]
+# loglevel:[LEVEL] :show or change loglevel [0-6]
 function ove-loglevel {
 	set +x
-	if [ $# -eq 1 ] && ! [[ "${1}" =~ ^[0-5]$ ]]; then
-		echo "error: try 0-5"
+	if [ $# -eq 1 ] && ! [[ "${1}" =~ ^[0-6]$ ]]; then
+		echo "error: try 0-6"
 		return 1
 	elif [ $# -eq 1 ]; then
 		OVE_LOGLEVEL=$1
@@ -4274,6 +4593,7 @@ function ove-loglevel {
 		echo "3: execve timeline"
 		echo "4: execve time analysis"
 		echo "5: connect analysis"
+		echo "6: graph analysis"
 		break
 	done | grep -E --color "$|${OVE_LOGLEVEL}"
 
@@ -4836,6 +5156,13 @@ function ove_init {
 
 	if [ "${OVE_LOGLEVEL}" == "2" ]; then
 		set -x
+	fi
+
+	if ! [ -z "${OVE_ANALYZE_EXECVE+x}" ]; then
+		echo ${BASHPID} > ${OVE_PROJECT_TMP_DIR}/strace.pid
+		while true; do
+			[ -e ${OVE_PROJECT_TMP_DIR}/strace.cont ] && break
+		done
 	fi
 
 	[ "$1" == "quick" ] && return 0
