setup: use stderr

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -26,7 +26,7 @@
 set -e
 
 if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
-	cat << EOF
+	cat 1>&2 << EOF
 USAGE
 	setup <path> <url> [<rev>]
 
@@ -48,12 +48,12 @@ path="$1"
 url="$2"
 
 if [ -d "${path}" ]; then
-	echo "error: '${path}' already exist"
+	echo "error: '${path}' already exist" 1>&2
 	exit 1
 fi
 
 if ! command -v git > /dev/null; then
-	echo "error: 'git' is not found"
+	echo "error: 'git' is not found" 1>&2
 	exit 1
 fi
 
@@ -76,7 +76,7 @@ fi
 run() {
 	echo "${prompt} $*"
 	if ! eval "$*"; then
-		echo "error: '$*' failed"
+		echo "error: '$*' failed" 1>&2
 		exit 1
 	fi
 }
